# List the most errors associated with the most recent fetch
# of each Representation
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX scutter: <http://purl.org/net/scutter/>
SELECT ?source ?date ?error
WHERE
{
  ?representation scutter:source ?source.
  ?representation scutter:latestFetch ?fetch.
  ?fetch dc:date ?date.
  ?fetch scutter:error ?reason.
  ?reason dc:description ?error.
}
ORDER BY DESC(?date)
